config/routes.rb
Tagstest::Application.routes.draw do
  resources :fruits

end

app/models/fruit.rb
class Fruit < ActiveRecord::Base
  attr_accessible :title, :tag_list
  acts_as_ordered_taggable

  #
  # Uncomment the after_save block below to test
  # >> p self.tag_list_change
  #   ["ripe, over-ripe", ["ripe", "over-ripe"]]
  # >> (rdb:80) p self.tag_list_change.first.class
  #   String
  # >> (rdb:80) p self.tag_list_change.last.class
  #   ActsAsTaggableOn::TagList

  #after_save do
  #  debugger
  #end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/fruits_controller.rb
class FruitsController < ApplicationController
  # GET /fruits
  # GET /fruits.json
  def index
    @fruits = Fruit.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @fruits }
    end
  end

  # GET /fruits/1
  # GET /fruits/1.json
  def show
    @fruit = Fruit.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @fruit }
    end
  end

  # GET /fruits/new
  # GET /fruits/new.json
  def new
    @fruit = Fruit.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @fruit }
    end
  end

  # GET /fruits/1/edit
  def edit
    @fruit = Fruit.find(params[:id])
  end

  # POST /fruits
  # POST /fruits.json
  def create
    @fruit = Fruit.new(params[:fruit])

    respond_to do |format|
      if @fruit.save
        format.html { redirect_to @fruit, notice: 'Fruit was successfully created.' }
        format.json { render json: @fruit, status: :created, location: @fruit }
      else
        format.html { render action: "new" }
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /fruits/1
  # PUT /fruits/1.json
  def update
    @fruit = Fruit.find(params[:id])

    respond_to do |format|
      if @fruit.update_attributes(params[:fruit])
        format.html { redirect_to @fruit, notice: 'Fruit was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @fruit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /fruits/1
  # DELETE /fruits/1.json
  def destroy
    @fruit = Fruit.find(params[:id])
    @fruit.destroy

    respond_to do |format|
      format.html { redirect_to fruits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/fruits_helper.rb
module FruitsHelper
end

app/views/fruits/_form.html.erb
<%= form_for(@fruit) do |f| %>
  <% if @fruit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@fruit.errors.count, "error") %> prohibited this fruit from being saved:</h2>

      <ul>
      <% @fruit.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :tags %><br />
    <%= f.select :tag_list, ActsAsTaggableOn::Tag.all.collect{|t| [t.name, t.name]}, {}, {:multiple => true} %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/fruits/edit.html.erb
<h1>Editing fruit</h1>

<%= render 'form' %>

<%= link_to 'Show', @fruit %> |
<%= link_to 'Back', fruits_path %>

app/views/fruits/index.html.erb
<h1>Listing fruits</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @fruits.each do |fruit| %>
  <tr>
    <td><strong><%= fruit.title %></strong> (tags: <%= fruit.tag_list %>)</td>
    <td><%= link_to 'Show', fruit %></td>
    <td><%= link_to 'Edit', edit_fruit_path(fruit) %></td>
    <td><%= link_to 'Destroy', fruit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Fruit', new_fruit_path %>

app/views/fruits/new.html.erb
<h1>New fruit</h1>

<%= render 'form' %>

<%= link_to 'Back', fruits_path %>

app/views/fruits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  <%= @fruit.title %>
</p>

<p>
  <b>Tags:</b>
  <%= @fruit.tag_list %>
</p>

<%= link_to 'Edit', edit_fruit_path(@fruit) %> |
<%= link_to 'Back', fruits_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tagstest</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>